#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/functions"

nginx-pre-reload() {
    local APP="$1"; verify_app_name "$APP"
    local SCRIPT_DIR="$DOKKU_ROOT/$APP/scripts/nginx-pre-reload.d"
    local DOKKU_APP_LISTENERS=$(plugn trigger network-get-listeners "$APP" "web")
    local NGINX_CONF="$DOKKU_ROOT/$APP/nginx.conf"

    dokku_log_verbose_stderr_quiet "Checking for nginx-pre-reload script ..."

    # Check if script directory exists
    if [[ ! -d "$SCRIPT_DIR" ]]; then
        dokku_log_verbose_stderr_quiet "No scripts found."
        return 0
    fi

    dokku_log_verbose_stderr_quiet "Running nginx-pre-reload scripts in $SCRIPT_DIR ..."

    # Run scripts
    run_scripts_in_dir "$SCRIPT_DIR" "$APP" "$NGINX_CONF" "$DOKKU_APP_LISTENERS"
}

nginx-pre-reload "$@"
